name: Season Watcher

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"  # Every day at 12:00 UTC

jobs:
  check-season:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install beautifulsoup4 requests

      - name: Run season watcher script
        run: python3 season_watcher.py
