name: Season Watcher

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"  # Daily at 12:00 UTC

jobs:
  check-season:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install beautifulsoup4 requests

      - name: Run season watcher script
        run: python3 season_watcher.py

      - name: Trigger Peak TPE Tracker
        if: success() && env.NEW_SEASON_FOUND == 'true'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Track Peak TPE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
