name: Season Watcher

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 12:00 UTC
  push:
    branches:
      - main

jobs:
  check_offseason_post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run season watcher script
        run: |
          python3 season_watcher.py

      - name: Trigger peak TPE fetch if new season found
        if: steps.run_season_watcher.outputs.newSeason == 'true'
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: run-peak-tpe-fetch
